# Generated by Django 4.0.3 on 2022-04-06 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_alter_user_profile_photo_alter_user_role'),
        ('blog', '0006_alter_blog_content_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=5000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', through='blog.BlogContributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=128, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='picture'),
        ),
    ]
